baseURL: 'https://blog.black-desk.cn'
languageCode: 'zh-cn'
defaultContentLanguage: 'zh-cn'
title: 'RAMBLE&BB'
theme: 'PaperMod'
markup:
  defaultMarkdownHandler: 'pandoc'
security:
  exec:
    allow:
      - '^dart-sass-embedded$'
      - '^go$'
      - '^npx$'
      - '^postcss$'
      - '^pandoc$'
params:
  homeInfoParams:
    Title: "RAMBLE&BB"
    Content: "a place to write myself down"
    socialIcons:
      - name: "twitter"
        url: "https://twitter.com/black__desk"
      - name: "github"
        url: "https://github.com/black-desk"
      - name: "telegram"
        url: "https://t.me/black_desk"
outputs:
  home:
    - 'HTML'
    - 'RSS'
