baseURL = 'https://black-desk.github.io'
languageCode = 'zh-cn'
title = 'RAMBLE&BB'
theme = 'PaperMod'
publishDir = 'docs'
[markup]
        defaultMarkdownHandler = 'pandoc'
[security]
        [security.exec]
                allow = [
                        '^dart-sass-embedded$',
                        '^go$',
                        '^npx$',
                        '^postcss$',
                        '^pandoc$'
                ]
